# Setup
title: RUTC
url: https://unofficial-rutc.netlify.app/
baseurl: ""
site_name: Rock Under The Clock
image: assets/img/home_c.jpg
description: Chania's landmark festival and an experience you don't want to miss. Rock Under The Clock Festival is here!
author: Dimitris Pramateftakis
github: https://github.com/dimpram
exclude: ["README.md"]

# Plugins
plugins:
  - jekyll-paginate-v2

# Collections
collections:
  festivals:
    output: true
  streets:
    output: true
  bands:
    output: true
  locations:
    output: true
  workshops:
    output: true
  videos:
    output: true
  photos:
    output: true

# Defaults
permalink: pretty

pagination:
  enabled: true
  debug: false
  collection: "posts" # The default document collection to paginate if nothing is specified ('posts' is default)
  per_page: 3
  permalink: "/:num.html" # Pages are index.html inside this folder (default)
  title: ":title" # Optional the title format for the paginated pages
  limit: 0 # Limit how many pagenated pages to create (default: 0, means all)
  sort_field: "title"
  sort_reverse: false
  category: "posts" # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  tag: "" # Optional, the default tag to use, omit to disable
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  trail:
    before: 10
    after: 10
  extension: html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "standard"
      footer:
        text: "Join this year's festival!"
        btn: "Join the Event"
        link:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "festivals"
    values:
      layout: "info"
      gallery: true
      footer:
        text: "Join this year's festival!"
        btn: "Join the Event"
        link:
  - scope:
      path: ""
      type: "streets"
    values:
      layout: "standard"
      gallery: true
      footer:
        text: "Join this year's Street event!"
        btn: "Join the Event"
        link:
  - scope:
      path: ""
      type: "bands"
    values:
      layout: "standard"
      gallery: true
      footer:
        text: "Join this year's Street event!"
        btn: "Join the Event"
        link:
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "standard"
      gallery: true
      footer:
        text: "Join this year's Street event!"
        btn: "Join the Event"
        link:
  - scope:
      path: "assets/img"
    values:
      image: true

