title: RUTC
baseurl: /RUTC-Webpage
exclude: ['README.md']
plugins:
  - jekyll-paginate

collections:
  festivals:
    output: true
  streets:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "standard"
      footer:
        text: "Join this year's festival!"
        btn: "Join the Event"
        link: 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "festivals"
    values:
      layout: "standard"
      gallery: true
      footer:
        text: "Join this year's festival!"
        btn: "Join the Event"
        link:
  -
    scope:
      path: ""
      type: "streets"
    values:
      layout: "standard"
      gallery: true
      footer:
        text: "Join this year's Street event!"
        btn: "Join the Event"
        link: