title: RUTC
baseurl: /RUTC-Webpage
exclude: ['README.md']
plugins:
  - jekyll-paginate

collections:
  festivals:
    output: true
  streets:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "standard"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "festivals"
    values:
      layout: "info"
  -
    scope:
      path: ""
      type: "streets"
    values:
      layout: "info"